spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/adm_videos
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
