keycloak:
  realm: test
  host: http://test:8443

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  jpa:
    show-sql: true
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: 123456
    url: jdbc:h2:mem:/adm_videos_test # É possível persistir em um arquivo alterando "mem:adm_videos_test" para "file:./.h2/dev"
  h2:
    console:
      enabled: true
      path: /h2
